name: Build APK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Deps
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev build-essential
          pip install --upgrade pip
          pip install buildozer "cython<3"
      - name: Build
        run: buildozer -v android debug
      - uses: actions/upload-artifact@v4
        with:
          name: CheryVIN-APK
          path: bin/*.apk
