name: Build CheryVIN APK
on:
workflow_dispatch:
jobs:
build:
runs-on: ubuntu-latest
steps:
uses: actions/checkout@v4
name: Set up Python
uses: actions/setup-python@v5
with:
python-version: '3.10'
name: Install system dependencies and ACCEPT LICENSES (强力修复版)
run: |
sudo apt update
