name: Build CheryVIN APK

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build APK with buildozer‑action
        uses: kivy/buildozer-action@v1
        with:
          buildozer_args: android debug

      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: CheryVIN‑APK
          path: bin/*.apk
